apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: lucas-elk
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.lucas-elk.svc.cluster.local:9200"]
        index => "game-logs-%{+YYYY.MM.dd}"
      }
    }
