spring:
    application:
        name: lucas

    datasource:
        url: jdbc:postgresql://localhost:5432/lucas
        username: lucas
        password: lucas
        driver-class-name: org.postgresql.Driver

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - profile
                            - email

    jwt:
        secret: ${JWT_SECRET}
        access-token-expiration: 1800000      # 30분 (ms)
        refresh-token-expiration: 1209600000  # 14일 (ms)

  data:
    redis:
      host: lucas-redis-local
      port: 6379

server:
  port: 8080
