spring:
    application:
        name: lucas

    datasource:
        url: jdbc:postgresql://localhost:5432/lucas
        username: lucas
        password: lucas
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        show-sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - profile
                            - email

server:
  port: 8080
