input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    convert => {
      "elapsed_time_ms" => "integer"
    }
    lowercase => [ "input_value" ]
    strip => [ "input_value" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "game-logs-%{+YYYY.MM.dd}"
  }
}
