input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /StoryActionLogger/ {
    grok {
      match => { "message" => "StoryActionLogger\s*:\s*%{GREEDYDATA:json_payload}" }
    }
    json {
      source => "json_payload"
    }
    mutate {
      remove_field => ["json_payload"]
    }
  } else {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "game-logs-%{+YYYY.MM.dd}"
  }
}
